package com.si7ateck.dz.ui.types

enum class City {
    ADRAR,CHLEF,LAGHOUAT,OUM_EL_BOUAGHI,BATNA,BEJAIA,BISKRA,BECHAR,BLIDA,BOUIRA,TAMANRASSET,TEBESSA,TLEMCEN,TIARET,TIZI_OUZOU,ALGER,DJELFA,JIJEL,SETIF,SAIDA,SKIKDA,SIDI_BEL_ABBES,ANNABA,GUELMA,CONSTANTINE,MEDEA,MOSTAGANEM,MSILA,MASCARA,OUARGLA,ORAN,EL_BAYADH,ILLIZI,BORDJ_BOU_ARRERIDJ,BOUMERDES,EL_TAREF,TINDOUF,TISSEMSILT,EL_OUED,KHENCHeLA,SOUK_AHRAS,TIPAZA,MILA,AIN_DEFLA,NAAMA,AIN_TEMOUCHENT,GHARDAIA,RELIZANE
}